const HomeProduct = [
  {
    id: 1,
    Name: "Acer Led LCD",
    price: "26",
    image: "image/p1.webp",
    cat: "tv",
    type: "new",
  },
  {
    id: 2,
    Name: "Lenovo IdeaPad ",
    price: "96",
    image: "image/p2.webp",
    cat: "laptop",
    type: "new",
  },
  {
    id: 3,
    Name: "Apple Iwatch",
    price: "236",
    image: "image/p3.webp",
    cat: "watch",
    type: "new",
  },
  {
    id: 4,
    Name: "Samsung Tablet",
    price: "636",
    image: "image/p9.jpg",
    cat: "laptop",
    type: "new",
  },
  {
    id: 5,
    Name: "Amazon Alexa",
    price: "98",
    image: "image/p4.webp",
    cat: "speaker",
    type: "featured",
  },
  {
    id: 6,
    Name: "Itex CCTV",
    price: "59",
    image: "image/p5.webp",
    cat: "electronics",
    type: "featured",
  },
  {
    id: 7,
    Name: "SkullCandy Bash",
    price: "956",
    image: "image/p10.jpg",
    cat: "headphone",
    type: "featured",
  },
  {
    id: 8,
    Name: "LCD Watch",
    price: "389",
    image: "image/p11.jpg",
    cat: "electronics",
    type: "featured",
  },
  {
    id: 9,
    Name: "Mi Note10",
    price: "67",
    image: "image/p6.webp",
    cat: "phone",
    type: "top",
  },
  {
    id: 10,
    Name: "Bass Speaker",
    price: "76",
    image: "image/p7.webp",
    cat: "speaker",
    type: "top",
  },
  {
    id: 11,
    Name: "boAt Airdopes 311",
    price: "87",
    image: "image/p8.webp",
    cat: "speaker",
    type: "top",
  },
  {
    id: 12,
    Name: "Canon EOS",
    price: "807",
    image: "image/p12.webp",
    cat: "speaker",
    type: "top",
  },
];

export default HomeProduct;
