const ShopProduct = [
  {
    id: 1,
    Name: "EvoFox Blaze Mouse",
    price: "26",
    image: "image/i1.jpg",
    cat: "tv",
    type: "new",
  },
  {
    id: 2,
    Name: "LEvoFox Elite GamePad",
    price: "96",
    image: "image/i2.webp",
    cat: "laptop",
    type: "new",
  },
  {
    id: 3,
    Name: "Zebronics Headphone",
    price: "236",
    image: "image/i3.jpg",
    cat: "watch",
    type: "new",
  },
  {
    id: 4,
    Name: "Ant Esports Keyboard",
    price: "636",
    image: "image/i4.jpg",
    cat: "laptop",
    type: "new",
  },
  {
    id: 5,
    Name: "Logitech Driving",
    price: "98",
    image: "image/i5.webp",
    cat: "speaker",
    type: "featured",
  },
  {
    id: 6,
    Name: "Cosmic Cooling Pad",
    price: "59",
    image: "image/i6.webp",
    cat: "electronics",
    type: "featured",
  },
  {
    id: 7,
    Name: "BL Partybox",
    price: "956",
    image: "image/i7.webp",
    cat: "headphone",
    type: "featured",
  },
  {
    id: 8,
    Name: "LLogitech Webcamp",
    price: "389",
    image: "image/i8.webp",
    cat: "electronics",
    type: "featured",
  },
  {
    id: 9,
    Name: "HP Printer",
    price: "67",
    image: "image/i9.jpg",
    cat: "phone",
    type: "top",
  },
  {
    id: 10,
    Name: "MousePad",
    price: "76",
    image: "image/i10.webp",
    cat: "speaker",
    type: "top",
  },
  {
    id: 11,
    Name: "Apple iPad",
    price: "87",
    image: "image/i11.jpg",
    cat: "speaker",
    type: "top",
  },
  {
    id: 12,
    Name: "Amazfit GTR 4 ",
    price: "807",
    image: "image/i12.webp",
    cat: "speaker",
    type: "top",
  },
];

export default ShopProduct;
